In [36]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

In [37]:
data = pd.read_csv("car-mpg.csv")    

mpg = data.copy()

display("Info of the dataset:",mpg.info())
display("Head of the dataset:",mpg.head())
display("Tail of the dataset:",mpg.tail())
display("Shape of the dataset:",mpg.shape)
display("Description of the dataset:",mpg.describe(include='all').T)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64
 2   disp      398 non-null    float64
 3   hp        398 non-null    object
 4   wt        398 non-null    int64
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64
 7   origin    398 non-null    int64
 8   car_type  398 non-null    int64
 9   car_name  398 non-null    object
dtypes: float64(3), int64(5), object(2)
memory usage: 31.2+ KB

'Info of the dataset:'

None

'Head of the dataset:'

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino

'Tail of the dataset:'

      mpg  cyl   disp  hp    wt   acc  yr  origin  car_type         car_name
393  27.0    4  140.0  86  2790  15.6  82       1         1  ford mustang gl
394  44.0    4   97.0  52  2130  24.6  82       2         1        vw pickup
395  32.0    4  135.0  84  2295  11.6  82       1         1    dodge rampage
396  28.0    4  120.0  79  2625  18.6  82       1         1      ford ranger
397  31.0    4  119.0  82  2720  19.4  82       1         1       chevy s-10

'Shape of the dataset:'

(398, 10)

'Description of the dataset:'

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
mpg,398.0,NaN,NaN,NaN,23.514573,7.815984,9.0,17.5,23.0,29.0,46.6
cyl,398.0,NaN,NaN,NaN,5.454774,1.701004,3.0,4.0,4.0,8.0,8.0
disp,398.0,NaN,NaN,NaN,193.425879,104.269838,68.0,104.25,148.5,262.0,455.0
hp,398,94,150,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wt,398.0,NaN,NaN,NaN,2970.424623,846.841774,1613.0,2223.75,2803.5,3608.0,5140.0
acc,398.0,NaN,NaN,NaN,15.56809,2.757689,8.0,13.825,15.5,17.175,24.8
yr,398.0,NaN,NaN,NaN,76.01005,3.697627,70.0,73.0,76.0,79.0,82.0
origin,398.0,NaN,NaN,NaN,1.572864,0.802055,1.0,1.0,1.0,2.0,3.0
car_type,398.0,NaN,NaN,NaN,0.530151,0.499718,0.0,0.0,1.0,1.0,1.0
car_name,398,305,ford pinto,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
display(mpg['origin'].value_counts())
display(mpg['car_type'].value_counts())
display(mpg['car_name'].value_counts())

origin
1    249
3     79
2     70
Name: count, dtype: int64

car_type
1    211
0    187
Name: count, dtype: int64

car_name
ford pinto             6
toyota corolla         5
amc matador            5
ford maverick          5
chevrolet chevette     4
                      ..
chevrolet monza 2+2    1
ford mustang ii        1
pontiac astro          1
amc pacer              1
chevy s-10             1
Name: count, Length: 305, dtype: int64

In [39]:
mpg.isnull().sum()

mpg         0
cyl         0
disp        0
hp          0
wt          0
acc         0
yr          0
origin      0
car_type    0
car_name    0
dtype: int64

In [40]:
mpg = mpg.drop('car_name',axis=1)
mpg['origin'] = mpg['origin'].replace({1: 'america', 2: 'europe', 3: 'asia'})
mpg = pd.get_dummies(mpg, columns=['origin'])
mpg = mpg.replace('?', np.nan)

In [41]:
display(mpg.describe().T)

,count,mean,std,min,25%,50%,75%,max
mpg,398.0,23.514573,7.815984,9.0,17.500,23.0,29.000,46.6
cyl,398.0,5.454774,1.701004,3.0,4.000,4.0,8.000,8.0
disp,398.0,193.425879,104.269838,68.0,104.250,148.5,262.000,455.0
wt,398.0,2970.424623,846.841774,1613.0,2223.750,2803.5,3608.000,5140.0
acc,398.0,15.568090,2.757689,8.0,13.825,15.5,17.175,24.8
yr,398.0,76.010050,3.697627,70.0,73.000,76.0,79.000,82.0
car_type,398.0,0.530151,0.499718,0.0,0.000,1.0,1.000,1.0

In [42]:
X = mpg.drop('mpg', axis=1)
y = mpg['mpg']

import sklearn.preprocessing as preprocessing

X_Scaled = pd.DataFrame(preprocessing.scale(X))

In [46]:
display(X.head())
display(X_Scaled.head())

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,8,307.0,130,3504,12.0,70,0,True,False,False
1,8,350.0,165,3693,11.5,70,0,True,False,False
2,8,318.0,150,3436,11.0,70,0,True,False,False
3,8,304.0,150,3433,12.0,70,0,True,False,False
4,8,302.0,140,3449,10.5,70,0,True,False,False

,0,1,2,3,4,5,6,7,8,9
0,1.498191,1.090604,0.664133,0.630870,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
1,1.498191,1.503514,1.574594,0.854333,-1.477038,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
2,1.498191,1.196232,1.184397,0.550470,-1.658577,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
3,1.498191,1.061796,1.184397,0.546923,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
4,1.498191,1.042591,0.924265,0.565841,-1.840117,-1.627426,-1.062235,0.773559,-0.497643,-0.461968

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X_Scaled, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(318, 10) (80, 10) (318,) (80,)